### ISSUE TITLE
Shall we rename the repository?

### ISSUE THREAD

**Issue by gmacario** [robotrokers/rokers-yocto-distro#14]
To make things clearer for the people who will visit this repo I propose to rename it to something like `rokers-yocto-distro` or `rokers-yocto-linux`.

Anyway the repo should still remain a proper fork of upstream https://github.com/GENIVI/genivi-dev-platform

@ludusrusso: What is your opinion?

**Comment by ludusrusso** [comment]
@gmacario I like very much `rokers-yocto-distro`! If you agree, I'll change the name!

**Comment by gmacario** [comment]
Yes, please go ahead

**Comment by ludusrusso** [comment]
done!

**Comment by ludusrusso** [comment]
@gmacario the rename breaks jenkins..

**Comment by gmacario** [comment]
ACK, let's deal with it after merging #16

**Comment by gmacario** [comment]
Repository robotrokers/genivi-dev-platform renamed to https://github.com/robotrokers/rokers-yocto-distro

Jenkins Pipeline on https://build.rokers.io/ recreated and scratch build successful.
See https://build.rokers.io/job/robotrokers/job/rokers-yocto-distro/

Closing issue
