### ISSUE TITLE
Improve branch naming conventions

### ISSUE THREAD

**Issue by gmacario** [robotrokers/rokers-yocto-distro#7]
As of 2017-06-29 16:00 CEST, the following branches exist in https://github.com/robotrokers/genivi-dev-platform

* `dev-robots` - default branch
* `master` - supposed to be in sync with upstream https://github.com/GENIVI/genivi-dev-platform

However the default image being built is called `rokers-image-base`.

In order to reduce confusion I propose to rename our development branch to `dev-rokers`, then create `master-rokers`, `release-rokers`, etc wherever appropriate.

@ludusrusso Any different opinions?

**Comment by ludusrusso** [comment]
no its perfect!

**Comment by gmacario** [comment]
OK, I just renamed the branch `dev-robots` to `dev-rokers` and set it to default branch.
This will be our development branch from now on.

We shall discuss when we are going to create `master-rokers` - most likely after implementing CI/CD with easy-jenkins.
